Update celo-bls-go to v0.3.3
celo-org/celo-blockchain pull request #1946
Opened 2022-09-16 21:11 UTC by mstraka100

### Description

Updates the `celo-bls-go` dependency to `v0.3.3`. This adds several new architectures that the dependency can be compiled to, including that used by MacBook M1 chips.

### Tested

CI tests

### Backwards compatibility

The functionality of celo-bls-go has not changed with the update. No architectures were removed.

2022-09-16 21:13 UTC, piersy commented
Coverage from tests in `./e2e_test/...` for `./consensus/istanbul/...` at commit 0f304caffac0a3b7971253af098e7593edea791f
<details><summary>coverage:  50.6% of statements across all listed packages</summary><br>
<pre>
coverage:  64.0% of statements in consensus/istanbul
coverage:  42.7% of statements in consensus/istanbul/announce
coverage:  55.7% of statements in consensus/istanbul/backend
coverage:   0.0% of statements in consensus/istanbul/backend/backendtest
coverage:  24.3% of statements in consensus/istanbul/backend/internal/replica
coverage:  65.8% of statements in consensus/istanbul/core
coverage:  50.0% of statements in consensus/istanbul/db
coverage:   0.0% of statements in consensus/istanbul/proxy
coverage:  64.4% of statements in consensus/istanbul/uptime
coverage:  51.8% of statements in consensus/istanbul/validator
coverage:  79.2% of statements in consensus/istanbul/validator/random
</pre>
CommentID: 29c6c9cdca
</details>

2022-09-19 11:13 UTC, palango commented
Builds fine for me.

2022-09-23 16:07 UTC, mstraka100 commented on go.sum
>  github.com/celo-org/celo-bls-go v0.2.4/go.mod h1:eXUCLXu5F1yfd3M+3VaUk5ZUXaA0sLK2rWdLC1Cfaqo=
Should they be? They weren't automatically so I assumed it was some kind of Go idiom to leave in commit locks for previous dependency versions

2022-09-23 16:08 UTC, palango commented on go.sum
>  github.com/celo-org/celo-bls-go v0.2.4/go.mod h1:eXUCLXu5F1yfd3M+3VaUk5ZUXaA0sLK2rWdLC1Cfaqo=
I was asking out of interest as I'm also new to Go. I don't see a reason why it should stay, so I hoped you have an explanation for me.

2022-09-23 16:17 UTC, palango approved these changes
The open question doesn't block this.

2022-09-23 16:24 UTC, piersy requested changes
I've submitted a pr that simply tidies the go modules, please check that - https://github.com/celo-org/celo-blockchain/pull/1959

2022-09-23 17:26 UTC, piersy commented on go.sum
>  github.com/celo-org/celo-bls-go v0.2.4/go.mod h1:eXUCLXu5F1yfd3M+3VaUk5ZUXaA0sLK2rWdLC1Cfaqo=
The go commands can easily automatically add missing dependencies but in order to remove dependencies you need to run a command that takes into account the whole scope of the project, and that would be `go mod tidy`.

See [here](https://go.dev/blog/using-go-modules#TOC_7.) for a more detailed description.

Also I raised a PR doing the tidy here - https://github.com/celo-org/celo-blockchain/pull/1959

2022-09-26 09:04 UTC, piersy approved these changes
Looking good now!

2022-09-26 11:11 UTC, merged