Fix tracer block context
celo-org/celo-blockchain pull request #1987
Opened 2022-12-02 20:07 UTC by gastonponti

### Description

The tracer was not using the same block context for every tx (it was generating a new context for every tx)

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

Yes

2022-12-02 20:10 UTC, piersy commented
Coverage from tests in `./e2e_test/...` for `./consensus/istanbul/...` at commit d60bdd21e48f1f41cd655cde237e52df54f10482
<details><summary>coverage:  47.4% of statements across all listed packages</summary><br>
<pre>
coverage:  52.4% of statements in consensus/istanbul
coverage:  42.9% of statements in consensus/istanbul/announce
coverage:  56.0% of statements in consensus/istanbul/backend
coverage:   0.0% of statements in consensus/istanbul/backend/backendtest
coverage:  24.3% of statements in consensus/istanbul/backend/internal/replica
coverage:  54.6% of statements in consensus/istanbul/core
coverage:  50.0% of statements in consensus/istanbul/db
coverage:   0.0% of statements in consensus/istanbul/proxy
coverage:  64.4% of statements in consensus/istanbul/uptime
coverage:  51.8% of statements in consensus/istanbul/validator
coverage:  79.2% of statements in consensus/istanbul/validator/random
</pre>
CommentID: 442e2e816d
</details>

2022-12-05 10:38 UTC, piersy requested changes
Hey @gastonponti I think this change may re-introduce a problem that I previously fixed.

* #1860 

StateDB instances are not safe for concurrent use, so you have to use a copy, or ensure that all interaction is done in a single thread.

-------
Update:

@gastonponti Following our conversation I believe that this actually is safe. In #1860 I was incorrectly building the block context using the intermediate state after each transaction application, where in fact the block context is intended to be constructed with the state at the beginning of the block and re-used for all transactions in a block. This was causing the results of block tracing to diverge from execution in the case that any transaction affected the results given by the block context. 

Looking at the `SysContractCallCtx` constructor I can see that the provided `StateDB` is only used in the constructor and not retained by the struct, this makes the `SysContractCallCtx` safe for concurrent use.

2022-12-05 22:35 UTC, hbandura approved these changes

2022-12-06 12:05 UTC, piersy approved these changes
Looks good

2022-12-06 14:21 UTC, merged