Bump go version to 1.19
celo-org/celo-blockchain pull request #2189
Opened 2023-09-23 18:44 UTC by hbandura

Upstream cherry pick of go19 build & Dockerfile bump. A godoc whitespace change in go19 provoked many changes in the code.

2023-09-25 05:27 UTC, karlb approved these changes
Looks good, with the exception of the lint failures.

2023-09-25 05:27 UTC, karlb commented on .golangci.yml
> +    - whitespace
These cause plenty of [new lint failures](https://github.com/celo-org/celo-blockchain/actions/runs/6285414958/job/17067791540?pr=2189). So either we do not add these checks, or we fix the resulting failures.

2023-09-25 10:40 UTC, carterqw2 requested changes

2023-09-25 10:40 UTC, carterqw2 commented on accounts/usbwallet/ledger.go
> +//	Ethereum address length | 1 byte
Is it intentional?

2023-09-25 10:40 UTC, carterqw2 commented on build/ci.go
> +	archive    [ -arch architecture ] [ -type zip|tar ] [ -signer key-envvar ] [ -signify key-envvar ] [ -upload dest ] -- archives build artifacts
Did we support this option?

2023-09-25 10:40 UTC, carterqw2 commented on trie/stacktrie.go
> +// 2. The rlp-encoded value was < 32 bytes
Duplicate.

2023-09-26 05:45 UTC, hbandura commented on accounts/usbwallet/ledger.go
> +//	Ethereum address length | 1 byte
not intentional!

2023-09-27 11:19 UTC, carterqw2 approved these changes

2023-10-04 14:07 UTC, merged